[package]
name = "aes_tbox"
version = "0.1.0"
authors = ["Stefan Hausotte <stefan.hausotte@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
